# Generated by Django 4.1.1 on 2022-09-24 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Album name')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('private_album', models.BooleanField(default=False, verbose_name='Private Album')),
                ('album_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_author', to=settings.AUTH_USER_MODEL, verbose_name='Album Author')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_img', models.ImageField(upload_to='photo_img', verbose_name='Photo Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('private_photo', models.BooleanField(default=False, verbose_name='Private photo')),
                ('album', models.ManyToManyField(related_name='album', to='photo.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
