# Generated by Django 4.1.1 on 2022-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='album', to='photo.album'),
        ),
    ]
