# Generated by Django 4.1.1 on 2022-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(blank=True, related_name='albums', to='photo.album'),
        ),
    ]
