# Generated by Django 4.1.1 on 2022-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(related_name='photos', to='photo.photo'),
        ),
    ]
